# SPDX-License-Identifier: GPL-2.0-or-later
---
- name: Check if we have a valid temp folder
  ansible.builtin.stat:
    path: '{{ libvirt_provision_temp_path }}'
  register: folder_stat

- name: Create the the temp folder if it does not exists
  ansible.builtin.file:
    path: '{{ libvirt_provision_temp_path }}'
    state: directory
    mode: '0755'
  when: not folder_stat.stat.exists

- name: Combine default and custom config for VMs with network net_config
  ansible.builtin.set_fact:
    running_virtual_machines: "{{ running_virtual_machines | default([]) + [libvirt_provision_virtual_machine_config | combine(item) |
      combine({'net_config': libvirt_provision_virtual_machine_net_config}) | combine(item, recursive=True)] }}"
  loop: "{{ libvirt_provision_virtual_machines }}"
  loop_control:
    label: '{{ item.name }}'
  when: item.net_config is defined and item.net_config != {}

- name: Combine default and custom config for the rest
  ansible.builtin.set_fact:
    running_virtual_machines: "{{ running_virtual_machines | default([]) + [libvirt_provision_virtual_machine_config | combine(item)] }}"
  loop: "{{ libvirt_provision_virtual_machines }}"
  loop_control:
    label: '{{ item.name }}'
  when: item.net_config | default({}) == {}

- name: Set temporary variables for cloud image information
  ansible.builtin.set_fact:
    cloud_image_name: "{{ libvirt_provision_distros[item.distro]['url'] | basename }}"
    cloud_image_url: "{{ libvirt_provision_distros[item.distro]['url'] }}"
    cloud_image_sha: "{{ libvirt_provision_distros[item.distro]['sha'] | default(omit) }}"
  loop: "{{ running_virtual_machines }}"
  loop_control:
    label: '{{ item.name }}'
  register: cloud_images_information

- name: Find unique cloud images to download, and ready to download
  ansible.builtin.set_fact:
    cloud_images_unique: "{{ cloud_images_information.results | map(attribute='ansible_facts') | unique | list }}"

- name: Download local copy of cloud images
  ansible.builtin.get_url:
    url: "{{ item.cloud_image_url }}"
    dest: "{{ libvirt_provision_temp_path }}/{{ item.cloud_image_name }}"
    mode: '0644'
    checksum: "{{ item.cloud_image_sha | default(omit) }}"
  loop: "{{ cloud_images_unique }}"
  loop_control:
    label: '{{ item.cloud_image_url }}'

- name: Create disk placeholder in storage pool
  ansible.builtin.command:
    argv:
      - virsh
      - --connect
      - "{{ libvirt_provision_connection }}"
      - vol-create-as
      - "{{ libvirt_provision_storage_pool }}"
      - "{{ item.name }}.qcow2"
      - "{{ item.disk_gb }}G"
      - --format
      - qcow2
  loop: "{{ running_virtual_machines }}"
  register: disk_placeholder
  loop_control:
    label: '{{ item.name }}.qcow2'
  ignore_errors: true
  failed_when: false
  changed_when: false
  when: state == "present"

- name: List new placeholders in storage pool
  ansible.builtin.command: echo
  loop: "{{ disk_placeholder.results }}"
  loop_control:
    label: '{{ item.item.name }}.qcow2'
  changed_when: true
  when:
    - state == "present"
    - item.rc == 0

- name: Import cloud image into placeholder
  ansible.builtin.command:
    argv:
      - virsh
      - --connect
      - "{{ libvirt_provision_connection }}"
      - vol-upload
      - "{{ item.item.name }}.qcow2"
      - "{{ libvirt_provision_temp_path }}/{{ libvirt_provision_distros[item.item.distro]['url'] | basename }}"
      - --sparse
      - --pool
      - "{{ libvirt_provision_storage_pool }}"
  loop: "{{ disk_placeholder.results }}"
  loop_control:
    label: '{{ item.item.name }}.qcow2'
  changed_when: true
  when:
    - state == "present"
    - item.rc == 0

- name: Resize VM disk
  ansible.builtin.command:
    argv:
      - virsh
      - --connect
      - "{{ libvirt_provision_connection }}"
      - vol-resize
      - "{{ item.item.name }}.qcow2"
      - "{{ item.item.disk_gb }}G"
      - --pool
      - "{{ libvirt_provision_storage_pool }}"
  loop: "{{ disk_placeholder.results }}"
  loop_control:
    label: '{{ item.item.name }}.qcow2'
  changed_when: true
  when:
    - state == "present"
    - item.rc == 0

- name: Populate temporary root password file
  ansible.builtin.copy:
    dest: '{{ lookup("pipe", "mktemp -u " + libvirt_provision_temp_path + "/ansible.XXXXXX") }}'
    mode: "0600"
    content: |
      {{ libvirt_provision_root_password }}
  register: temp_root_password

- name: Populate temporary ssh key file
  ansible.builtin.copy:
    dest: '{{ lookup("pipe", "mktemp -u " + libvirt_provision_temp_path + "/ansible.XXXXXX") }}'
    mode: "0600"
    content: |
      {{ libvirt_provision_root_ssh_key }}
  register: temp_ssh_key

- name: Store all temp file names
  ansible.builtin.set_fact:
    temp_files: '{{ [temp_root_password, temp_ssh_key] | selectattr("dest", "defined") | map(attribute="dest") | list }}'

- name: Wait for all temp files to exist, avoid race condition on fast computers
  ansible.builtin.wait_for:
    path: '{{ item }}'
  loop: '{{ temp_files }}'

- name: Create VMs
  community.libvirt.virt_install:
    uri: "{{ libvirt_provision_connection }}"
    name: "{{ item.name }}"
    memory: "{{ item.memory_mb }}"
    vcpus: "{{ item.vcpus }}"
    import: true
    osinfo:
      name: "{{ libvirt_provision_distros[item.distro]['os_variant'] }}"
    boot: "{{ libvirt_provision_distros[item.distro]['boot'] | default(omit) }}"
    disks:
      - vol: "{{ libvirt_provision_storage_pool }}/{{ item.name }}.qcow2"
        bus: virtio
        driver:
          discard: unmap
    cloud_init:
      disable: true
      clouduser_ssh_key: "{{ temp_ssh_key.dest | default(omit) }}"
      network_config: "{{ item.net_config | default(omit) }}"
      # {{ item.net_config | to_nice_yaml(indent=2) | default(omit) }}
      root_password_file: "{{ temp_root_password.dest | default(omit) }}"
    networks: "{{ item.networks | default(omit) }}"
    graphics:
      type: none
    state: "{{ state }}"
  loop: "{{ running_virtual_machines }}"
  loop_control:
    label: '{{ item.name }}'
  register: cmd_virt_install
  failed_when: false

- name: Result of VM operation
  ansible.builtin.debug:
    msg: "{{ item.msg }}"
  loop: "{{ cmd_virt_install.results }}"
  loop_control:
    label: '{{ item.item.name }}'
  when:
    - item.msg is defined

- name: Remove all temp files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ temp_files }}"

- name: Undefine VMs
  community.libvirt.virt:
    uri: "{{ libvirt_provision_connection }}"
    name: "{{ item.name }}"
    command: undefine
    flags:
      - nvram
  loop: "{{ running_virtual_machines }}"
  loop_control:
    label: '{{ item.name }}'
  failed_when: false
  when: state == "absent"
